apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "good-eatz-react.fullname" . }}-config
  labels:
    {{- include "good-eatz-react.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "API_BASE": {{- if and .Values.api.host .Values.api.port -}}
      "http://{{ .Values.api.host }}:{{ .Values.api.port }}"
      {{- else -}}
      ""
      {{- end }},
      "PHARMA_BASE": {{- if and .Values.pharma.host .Values.pharma.port -}}
      "http://{{ .Values.pharma.host }}:{{ .Values.pharma.port }}"
      {{- else -}}
      ""
      {{- end }}
    }
