apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "good-eatz-react.fullname" . }}-config
  labels:
    {{- include "good-eatz-react.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "API_BASE": "",
      "PHARMA_BASE": ""
    }
