apiVersion: v1
kind: Service
metadata:
  name: good-eatz-doctor-flask
spec:
  type: ExternalName
  externalName: good-eatz-doctor-flask.good-eatz-doctor-flask.svc.cluster.local
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
