replicaCount: 1
image:
  repository: cs490group6/react-good-eatz
  pullPolicy: Always
  tag: "latest"

gitCommit: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}
service:
  type: NodePort
  port: 80
  nodePort: 30003

ingress:
  enabled: false
  className: traefik           # or nginx, depending on your controller
  annotations: {}              # any extra annotations you need
  hosts:
    - host: localhost
      paths:
        # 1) UI path → your React Service on port 80
        - path: /
          pathType: ImplementationSpecific
          serviceName: good-eatz-react        # <— your frontend Service name
          servicePort: 80
        # 2) API path → your Flask Service on port 5000
        - path: /api
          pathType: ImplementationSpecific
          serviceName: good-eatz-doctor-flask  # <— your backend Service name
          servicePort: 5000
  tls: []

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

api:
  host: ""
  port: ""

pharma:
  host: ""
  port: ""
